
spring:
  application:
    name: asearch
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://34.96.156.43:3306?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:12345678}
  task:
    execution:
      pool:
        max-size: 1500
        core-size: 200
as:
  host: 34.96.156.43
  key-index: 1031
server:
  port: 7070

